name: Despliegue-App-React

on: push

jobs:
  build-statics:
    name: build-statics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Builds static files
        run: |
          npm install
          npm run build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

  deploy-surge:
    name: deploy-surge
    runs-on: ubuntu-latest
    needs: build-statics

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      
      - name: Deploy artifacts on surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'marctorres.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}